import { Download } from 'lucide-react'
import { AnalysisResults } from '../types'

interface ExportButtonProps {
  results: AnalysisResults
}

function buildExportText(results: AnalysisResults): string {
  const { patent_metadata, opportunities, scores, summary_brief } = results
  const timestamp = new Date().toISOString()

  const lines: string[] = [
    '═══════════════════════════════════════════════════════════════════════',
    '  PATENT INTELLIGENCE ENGINE — STRATEGY BRIEF',
    '═══════════════════════════════════════════════════════════════════════',
    `  Generated: ${timestamp}`,
    '',
    '───────────────────────────────────────────────────────────────────────',
    '  PATENT OVERVIEW',
    '───────────────────────────────────────────────────────────────────────',
    `  Title:    ${patent_metadata.title}`,
    `  Assignee: ${patent_metadata.assignee}`,
    `  Domain:   ${patent_metadata.technical_domain}`,
    `  Filed:    ${patent_metadata.filing_date}`,
    `  Inventors: ${patent_metadata.inventors.join(', ')}`,
    '',
    '  ABSTRACT',
    `  ${patent_metadata.abstract}`,
    '',
    '  PLAIN ENGLISH SUMMARY',
    `  ${patent_metadata.plain_english_summary}`,
    '',
    '───────────────────────────────────────────────────────────────────────',
    '  EXECUTIVE SUMMARY BRIEF',
    '───────────────────────────────────────────────────────────────────────',
    `  ${summary_brief}`,
    '',
    '───────────────────────────────────────────────────────────────────────',
    '  ANALYSIS SCORES',
    '───────────────────────────────────────────────────────────────────────',
    `  Total Opportunities Identified: ${scores.total_opportunities}`,
    `  Average Composite Score:        ${scores.avg_composite_score}/100`,
    `  Top Opportunity Domain:         ${scores.top_domain}`,
    `  Top Opportunity Score:          ${scores.top_score}/100`,
    '',
    '───────────────────────────────────────────────────────────────────────',
    '  TOP 3 CROSS-INDUSTRY OPPORTUNITIES',
    '───────────────────────────────────────────────────────────────────────',
  ]

  opportunities.forEach((opp, i) => {
    lines.push(
      '',
      `  #${i + 1} — ${opp.domain.toUpperCase()}`,
      `  Composite Score: ${opp.composite_score}/100`,
      '',
      `  Use Case: ${opp.use_case}`,
      `  ${opp.analogy_explanation}`,
      '',
      '  DIMENSION SCORES',
      `    Novelty:         ${opp.novelty}/100`,
      `    Modularity:      ${opp.modularity}/100`,
      `    Transferability: ${opp.transferability}/100`,
      `    Feasibility:     ${opp.feasibility}/100`,
      `    Market Potential:${opp.market_potential}/100`,
      '',
      '  SUPPORTING MODULES',
      `    ${opp.supporting_modules.join(' · ')}`,
      '',
      '  ⚡ ACTION RECOMMENDATION',
      `    ${opp.action_recommendation}`,
      '',
      '  STRATEGY BRIEF',
      `    ${opp.strategy_brief}`,
      '',
      '  · · · · · · · · · · · · · · · · · · · · · · · · · · · · · · · · ·',
    )
  })

  lines.push(
    '',
    '═══════════════════════════════════════════════════════════════════════',
    '  Generated by Patent Intelligence Engine',
    '  An agentic AI system for IP commercialization strategy',
    '═══════════════════════════════════════════════════════════════════════',
  )

  return lines.join('\n')
}

export default function ExportButton({ results }: ExportButtonProps) {
  const handleExport = () => {
    const content = buildExportText(results)
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    const safeName = results.patent_metadata.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .slice(0, 50)
    a.href = url
    a.download = `patent-strategy-${safeName}-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const previewText = buildExportText(results)

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-white font-semibold text-lg">Strategy Brief Export</h3>
          <p className="text-gray-400 text-sm mt-0.5">Download a complete text report of the analysis</p>
        </div>
        <button
          onClick={handleExport}
          className="flex items-center gap-2 px-5 py-2.5 bg-brand-purple hover:bg-brand-purple-dim
                     text-white font-medium rounded-lg transition-colors duration-200
                     shadow-lg shadow-brand-purple/20"
        >
          <Download size={16} />
          Download .txt
        </button>
      </div>

      <div className="bg-dark-bg border border-dark-border rounded-xl overflow-hidden">
        <div className="flex items-center gap-2 px-4 py-2.5 border-b border-dark-border bg-dark-card">
          <div className="w-3 h-3 rounded-full bg-red-500/70" />
          <div className="w-3 h-3 rounded-full bg-yellow-500/70" />
          <div className="w-3 h-3 rounded-full bg-green-500/70" />
          <span className="text-gray-500 text-xs ml-2 font-mono">strategy-brief.txt</span>
        </div>
        <pre className="text-xs text-gray-400 font-mono p-4 overflow-auto max-h-[480px] leading-relaxed whitespace-pre-wrap">
          {previewText}
        </pre>
      </div>
    </div>
  )
}
